ALTER TABLE challenges ALTER COLUMN client_domain DROP NOT NULL;
ALTER TABLE challenges ALTER COLUMN client_domain DROP DEFAULT;

ALTER TABLE sessions ALTER COLUMN memo DROP NOT NULL;
ALTER TABLE sessions ALTER COLUMN memo DROP DEFAULT;

ALTER TABLE sessions ALTER COLUMN client_domain DROP NOT NULL;
ALTER TABLE sessions ALTER COLUMN client_domain DROP DEFAULT;
